apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-echo
  labels:
    app: hello-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-echo
  template:
    metadata:
      labels:
        app: hello-echo
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Hello, World!"
          ports:
            - containerPort: 5678
